name: PR Check

on:
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: Test-Reports
          path: target/surefire-reports/
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: JAR-Artifact
          path: target/*.jar
